/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8-rc-1/userguide/building_java_projects.html
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.20"
    kotlin("plugin.serialization") version "1.4.20"
    application
}

repositories {
    jcenter()
}

dependencies {
    implementation("com.sparkjava:spark-core:2.9.3")
    implementation("com.sparkjava:spark-kotlin:1.0.0-alpha")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")
    testImplementation("io.cucumber:cucumber-java8:6.8.1")
    testImplementation("io.cucumber:cucumber-junit:6.8.1")
    testImplementation("io.rest-assured:rest-assured:4.3.2")
    testImplementation("org.assertj:assertj-core:3.6.1")
    implementation("khttp:khttp:0.1.0")
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2")
    implementation("com.google.guava:guava:29.0-jre")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    mainClass.set("hello.vehicle.AppKt")
}

tasks {
    task<JavaExec>("importCSV") {
        dependsOn("classes")
        val mainClassName = "hello.vehicle.ImportCsvKt"
        classpath = sourceSets["main"].runtimeClasspath
        main = mainClassName
    }
}
